#!/usr/bin/env python
# -*- coding: utf-8 -*-
import telebot
commandkeyboard = telebot.types.ReplyKeyboardMarkup(True)
commandkeyboard.row('⚙Настройки', '✍Последние рассылки')
infokeyboard = telebot.types.ReplyKeyboardMarkup(True)
infokeyboard.row('Мировые новости', 'Украинские новости', 'Новости технологий')
infokeyboard.row('Новости науки', 'Главные новости', 'Новости спорта')
infokeyboard.row('Харьк. новости', 'КоРоНаВиРуС', 'Ещё одни новости')
infokeyboard.row('Курсы валют', 'Акции', 'Погода', 'Праздник')
infokeyboard.row('Назад', 'Источники')

settingskeyboard = telebot.types.InlineKeyboardMarkup(row_width=1)
item1 = telebot.types.InlineKeyboardButton("Первая рассылка", callback_data='first_mail')
item2 = telebot.types.InlineKeyboardButton("Вторая рассылка", callback_data='second_mail')
settingskeyboard.add(item1, item2)

firsttimekeyboard = telebot.types.InlineKeyboardMarkup(row_width=1)
item0 = telebot.types.InlineKeyboardButton("ВЫКЛ", callback_data='first:off')
item1 = telebot.types.InlineKeyboardButton("5:00", callback_data='5:00')
item2 = telebot.types.InlineKeyboardButton("6:00", callback_data='6:00')
item3 = telebot.types.InlineKeyboardButton("7:00", callback_data='7:00')
item4 = telebot.types.InlineKeyboardButton("8:00", callback_data='8:00')
item5 = telebot.types.InlineKeyboardButton("9:00", callback_data='9:00')
item6 = telebot.types.InlineKeyboardButton("10:00", callback_data='10:00')
item7 = telebot.types.InlineKeyboardButton("11:00", callback_data='11:00')
item8 = telebot.types.InlineKeyboardButton("12:00", callback_data='12:00')
firsttimekeyboard.add(item0, item1, item2, item3, item4, item5, item6, item7, item8)

secondtimekeyboard = telebot.types.InlineKeyboardMarkup(row_width=1)
item0 = telebot.types.InlineKeyboardButton("ВЫКЛ", callback_data='second:off')
item1 = telebot.types.InlineKeyboardButton("13:00", callback_data='13:00')
item2 = telebot.types.InlineKeyboardButton("14:00", callback_data='14:00')
item3 = telebot.types.InlineKeyboardButton("15:00", callback_data='15:00')
item4 = telebot.types.InlineKeyboardButton("16:00", callback_data='16:00')
item5 = telebot.types.InlineKeyboardButton("17:00", callback_data='17:00')
item6 = telebot.types.InlineKeyboardButton("18:00", callback_data='18:00')
item7 = telebot.types.InlineKeyboardButton("19:00", callback_data='19:00')
item8 = telebot.types.InlineKeyboardButton("20:00", callback_data='20:00')
item9 = telebot.types.InlineKeyboardButton("21:00", callback_data='21:00')
item10 = telebot.types.InlineKeyboardButton("22:00", callback_data='22:00')
item11 = telebot.types.InlineKeyboardButton("23:00", callback_data='23:00')
secondtimekeyboard.add(item0, item1, item2, item3, item4, item5, item6, item7, item8, item9, item10, item11)
